# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "none";
      fsType = "tmpfs";
      options = [ "size=2G" "defaults" "mode=755" ];
    };

  fileSystems."/nix" =
    { device = "/dev/vda1";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/vda1";
      fsType = "btrfs";
      options = [ "subvol=var/log" ];
    };

  fileSystems."/persistent" =
    { device = "/dev/vda1";
      fsType = "btrfs";
      neededForBoot = true;
      options = [ "subvol=persistent" ];
    };

  fileSystems."/boot" =
    { device = "/dev/vda2";
      fsType = "vfat";
      options = [ "noauto" "x-systemd.automount" ];
    };

  swapDevices = [ ];

}
