#!/bin/bash
set -e

virsh='virsh -c qemu:///system'
vm=vm1
testdevice=c52b # Moruseman
batchone="$HOME/.config/win10vm/unifying.xml $HOME/.config/win10vm/microsoft.xml"
batchonetitle='Mouseman and Strafe'
batchtwo="$HOME/.config/win10vm/race3.xml $HOME/.config/win10vm/g502.xml"
batchtwotitle='Race3 and G502'

detachDevices() {
  for i in $@; do
    $virsh detach-device $vm $i
  done
}

attachDevices() {
  for i in $@; do
    $virsh attach-device $vm $i
  done
}

notify(){
  notify-send -t 5000 -i keyboard 'VM Device Swap' "$@"
}

startScript() {
  if $virsh list | grep -q $vm; then
    if $virsh dumpxml $vm | grep -q $testdevice; then
      detachDevices $batchone
      attachDevices $batchtwo
      notify "$batchtwotitle"
    else
      detachDevices $batchtwo
      attachDevices $batchone
      notify "$batchonetitle"
    fi
  fi
}

echo notify-send "$(startScript 2>&1)"
