# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ "${modulesPath}/installer/scan/not-detected.nix" ];

  boot.kernelModules = [ "kvm-intel" ];
  boot.zfs.requestEncryptionCredentials = true;
  ragon.system.fs.enable = true;
  ragon.system.fs.swap = false;
  swapDevices = [
    { device = "/dev/md1"; }

  ];
  services.syncoid.enable = false; # disable failing zfs syncing
  boot.initrd = {
    availableKernelModules = [ "ahci" "xhci_pci" "ehci_pci" "usbhid" "sd_mod" "sr_mod" ];
    network = {
      enable = true;
      postCommands = ''
       zpool import pool
       echo "zfs load-key -a; killall zfs" >> /root/.profile
      '';
      ssh = {
        enable = true;
        port = 2222;
        hostKeys = [
          "/etc/nixos/secrets/initrd/ssh_host_rsa_key"
          "/etc/nixos/secrets/initrd/ssh_host_ed25519_key"
        ];
        authorizedKeys = pkgs.pubkeys.ragon.computers;

      };

    };

  };

  powerManagement.cpuFreqGovernor = "performance";
}
