# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, inputs, ... }:
let
  pubkeys = import ../../data/pubkeys.nix;
in
{
  imports = [ "${modulesPath}/profiles/qemu-guest.nix" inputs.disko.nixosModules.disko ];
  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/d2cb12f8-67e3-4725-86c3-0b5c7ebee3a6";
  disko.devices = import ./disk-config.nix {
    inherit lib;
  };

  boot.initrd = {
    network = {
      enable = true;
      ssh = {
        enable = true;
        port = 2222;
        hostKeys = [
          "/persistent/etc/nixos/secrets/initrd/ssh_host_rsa_key"
          "/persistent/etc/nixos/secrets/initrd/ssh_host_ed25519_key"
        ];
        authorizedKeys = pubkeys.ragon.user;
      };
    };
  };
  powerManagement.cpuFreqGovernor = "performance";
}
