# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, inputs, ... }:
let
  pubkeys = import ../../data/pubkeys.nix;
in
{
  imports = [ "${modulesPath}/profiles/qemu-guest.nix" inputs.disko.nixosModules.disko ./disk-config.nix ];
  #boot.initrd.luks.devices."crypted".device = "/dev/vda2";

  boot.initrd = {
    network = {
      enable = true;
      ssh = {
        enable = true;
        port = 2222;
        hostKeys = [
          "/nix/persistent/etc/nixos/secrets/initrd/ssh_host_rsa_key"
          "/nix/persistent/etc/nixos/secrets/initrd/ssh_host_ed25519_key"
        ];
        authorizedKeys = pubkeys.ragon.user;
      };
    };
  };
  powerManagement.cpuFreqGovernor = "performance";
}
