# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "ehci_pci" "nvme" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ "vfio-pci" ];
  boot.initrd.luks.devices.crypt.device = "/dev/nvme0n1p1";
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "none";
      fsType = "tmpfs";
      options = [ "size=3G" "defaults" "mode=755" ];
    };
  fileSystems."/nix" =
    { device = "pool/nix";
      fsType = "zfs";
    };

  fileSystems."/persistent" =
    { device = "pool/persist";
      fsType = "zfs";
      neededForBoot = true;
    };

  fileSystems."/var/log" =
    { device = "pool/varlog";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BDC7-CFCC";
      fsType = "vfat";
      options = [ "noauto" "x-systemd.automount" ];
    };

  swapDevices = [ ];

}
